"https://{default}/": { type: upstream, upstream: "app:http", cache: { enabled: false } } 
"https://*.{default}/": { type: upstream, upstream: "app:http", cache: { enabled: false } } 

"https://{all}/": { type: redirect, to: "https://{default}/" }
"https://*.{all}/": { type: redirect, to: "https://*.{default}/" }
